const $=id=>document.getElementById(id);let timer=null,done=0,target=0;const alertAudio=new Audio("./assets/alert-tone.mp3");alertAudio.preload="auto";
const names=["Avery Cole","Jordan Ellis","Taylor Brooks","Riley Morgan","Casey Bennett","Quinn Parker","Jamie Reed","Rowan Hayes","Emerson Lane","Cameron Blake"];
const money=c=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD"}).format(c/100);
function status(on){$("statusDot").classList.toggle("on",on);$("status").textContent=on?`Running · ${done}/${target}`:`Stopped · ${done} generated`;}
function addOne(){const lo=Math.round(Number($("min").value)*100),hi=Math.round(Number($("max").value)*100);const cents=lo+Math.floor(Math.random()*(hi-lo+1));const items=1+Math.floor(Math.random()*3),name=names[Math.floor(Math.random()*names.length)],source=Math.random()<.82?"Online Store":"Social";
 const now=new Date(),time=now.toLocaleTimeString([], {hour:"numeric",minute:"2-digit"});
 const row=document.createElement("div");row.className="item";const bag=document.createElement("div");bag.className="bag";bag.textContent="▱";const details=document.createElement("div");details.className="details";const title=document.createElement("div");title.className="title";title.textContent="Shopify";const meta=document.createElement("div");meta.className="meta";meta.textContent=`${name} · ${items} ${items===1?"item":"items"} · ${time} · ${source}`;details.append(title,meta);const total=document.createElement("div");total.className="total";total.textContent=money(cents);row.append(bag,details,total);$("feed").prepend(row);$("feed").querySelector(".empty")?.remove();
 if("Notification"in window&&Notification.permission==="granted"){try{new Notification("Shopify",{body:`${items} ${items===1?"item":"items"} totaling ${money(cents)} from ${source}.`,icon:"./icon.svg",tag:"averta-test-"+done});}catch(e){}}
 done++;status(true);if(document.visibilityState==="visible"){alertAudio.currentTime=0;alertAudio.play().catch(()=>{});}if(done>=target)stop();}
function stop(){if(timer!==null)clearTimeout(timer);timer=null;$("start").disabled=false;$("stop").disabled=true;status(false);}
function next(){if(timer===null)return;addOne();if(timer!==null)timer=setTimeout(next,Number($("speed").value)*1000);}
$("start").addEventListener("click",async()=>{const n=Number($("count").value),a=Number($("min").value),b=Number($("max").value);if(!Number.isInteger(n)||n<1||n>100){alert("Choose 1–100 alerts.");return;}if(!Number.isFinite(a)||!Number.isFinite(b)||a<=0||b>360||a>b){alert("Set a valid range, with a maximum of $360.00.");return;}if("Notification"in window&&Notification.permission==="default"){try{await Notification.requestPermission()}catch(e){}}done=0;target=n;$("feed").innerHTML="";$("start").disabled=true;$("stop").disabled=false;status(true);timer=setTimeout(next,450);});
$("stop").addEventListener("click",stop);$("clear").addEventListener("click",()=>$("feed").innerHTML='<div class="empty">No alerts yet.</div>');
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));
